name: Chrisland CBT workflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/cbt_software
            git pull origin master
            docker compose up -d --build
            echo "Waiting for containers to initialize..."
            sleep 10
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan optimize
