name: Chrisland CBT workflow

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/cbt_software
            git pull origin master

            # 1. Physically create the manifest on the VPS disk
            docker run --rm -v $(pwd):/app -w /app node:20-alpine sh -c "npm install && npm run build"

            # 2. Start the project
            docker compose up -d --build

            # 3. Permissions & Laravel Commands
            sudo chown -R 33:33 storage bootstrap/cache public/build
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan optimize
